import {stringSchema as str, integerSchema as int, arraySchema as arr, toolSchema as tool} from '../../../core/schema.mjs';
const iface=str('Physical host interface; omit to select the default Ethernet/Wi-Fi interface.',{maxLength:64});
const ip=str('Authorized IPv4 address on the selected interface subnet.',{maxLength:15});
export const ISOLATION_TOOLS=[
 tool('observe_broadcast_multicast','Passively observe ARP, mDNS, LLMNR and SSDP on the physical host interface. Reports packet sources separately from claimed/advertised addresses, names and services. Sends no discovery packets. Visibility is evidence of delivered traffic, not proof of broken isolation.',{
  interface:iface,duration_seconds:int('Capture duration; default 10, maximum 30.',1,30),max_packets:int('Stop after this many matching packets; default 256, maximum 1000.',1,1000),max_observations:int('Maximum unique evidence rows; default 128, maximum 256.',1,256),protocols:arr('Protocols to observe; default all four.',str('Discovery protocol.',{enum:['arp','mdns','llmnr','ssdp']}),{minItems:1,maxItems:4,uniqueItems:true})}),
 tool('probe_gateway_proxy_arp','Bounded ARP sweep on a directly connected IPv4 subnet. Compares responding MACs with the gateway MAC and reports proxy-ARP candidates and shared MACs. Gateway responses do not prove that claimed peer IPs are active.',{
  interface:iface,cidr:str('Explicit directly connected IPv4 CIDR; omit to use selected local prefix. Oversized ranges are rejected.',{maxLength:18}),gateway:ip,max_hosts:int('Maximum addresses in the sweep; default 256, maximum 256.',1,256),timeout_seconds:int('Response wait after sending; default 2, maximum 5.',1,5)}),
 tool('probe_gateway_hairpin','Compare bounded ICMP echo delivery to explicit same-subnet peers using direct Ethernet and Ethernet addressed to the gateway. A TTL=1 gateway-path control provides forwarding evidence. Does not modify routes or neighbor tables. Results cannot establish isolation policy without a known controlled peer.',{
  interface:iface,gateway:ip,peer_targets:arr('Explicit known IPv4 peers on selected subnet; no automatic target expansion.',ip,{minItems:1,maxItems:8,uniqueItems:true}),probes:int('Echo probes per path per peer; default 1, maximum 3.',1,3),timeout_seconds:int('Wait per ARP/ICMP probe; default 1, maximum 2.',1,2)},['peer_targets']),
 tool('observe_dns_cache','Query explicit names on an authorized LAN DNS server with recursion disabled. Returns validated DNS answers, TTLs, authoritative/referral flags and response timing. Optional caller-supplied TTL baseline permits comparison. Never identifies a querying client or confirms device presence from cache data.',{
  interface:iface,server:ip,names:arr('Explicit hostnames or service domains; no built-in domain dictionary.',str('DNS name.',{maxLength:253}),{minItems:1,maxItems:16,uniqueItems:true}),record_type:str('DNS record type; default A.',{enum:['A','AAAA','PTR','SRV','TXT']}),samples:int('Repeated nonrecursive samples per name; default 2, maximum 3.',1,3),timeout_seconds:int('Wait per query; default 1, maximum 2.',1,2),baseline_ttl:int('Optional known original TTL for the queried RRset; never guessed or fetched automatically.',1,2147483647)},['names'])
];
export const ISOLATION_TOOL_NAMES=new Set(ISOLATION_TOOLS.map(t=>t.name));
